return {
	-- Vim Config
	{ "bo", "expandtab", true },
	{ "o", "background", "dark" },
	{ "o", "smartindent", true },
	{ "o", "shiftwidth", 2 },
	{ "o", "tabstop", 2 },
	{ "o", "softtabstop", 2 },
	{ "o", "autoindent", true },
	{ "o", "completeopt", "menu,menuone,noselect" },
	{ "o", "termguicolors", true },
	{ "o", "hidden", true },
	{ "o", "guifont", "Fira Code:14" },
	{ "o", "regexpengine", 1 },
	{ "o", "showmode", false },
	{ "o", "smartcase", true },
	{ "o", "splitbelow", true },
	{ "o", "splitright", true },
	{ "o", "mouse", "a" },
	{ "o", "scrolloff", 8 },
	{ "o", "sidescrolloff", 8 },
	{ "o", "scrollback", 8 },
	{ "o", "foldcolumn", "1" },
	{ "o", "foldlevelstart", 99 },
	{ "o", "foldlevel", 99 },
	{ "o", "foldenable", true },
	{ "o", "foldmethod", "expr" },
	{ "o", "fillchars", [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]] },
	{ "o", "foldexpr", "nvim_treesitter#foldexpr()" },
	{ "o", "formatexpr", "v:lua.require'conform'.formatexpr()" },
	{ "wo", "number", true },
	{ "wo", "relativenumber", true },
	{ "wo", "cursorline", true },

	{ "g", "did_load_filetypes", true },

	-- blame line
	{ "o", "updatetime", 300 },
	{ "o", "incsearch", false },
	{ "wo", "signcolumn", "yes" },
}
